# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BBVA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BBVA
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'SwiftyJSON'

end
