insert into giro (giro_id, nombre, descripcion) values (1, 'Finance', 'Investment Bankers/Brokers/Service');
insert into giro (giro_id, nombre, descripcion) values (2, 'Finance', 'Business Services');
insert into giro (giro_id, nombre, descripcion) values (3, 'Capital Goods', 'Fluid Controls');
insert into giro (giro_id, nombre, descripcion) values (4, 'Finance', 'Property-Casualty Insurers');
insert into giro (giro_id, nombre, descripcion) values (5, 'Public Utilities', 'Telecommunications Equipment');
insert into giro (giro_id, nombre, descripcion) values (6, 'Health Care', 'Major Pharmaceuticals');
insert into giro (giro_id, nombre, descripcion) values (7, 'Technology', 'EDP Services');
insert into giro (giro_id, nombre, descripcion) values (8, 'Finance', 'Banks');
insert into giro (giro_id, nombre, descripcion) values (9, 'Capital Goods', 'Auto Parts:O.E.M.');
insert into giro (giro_id, nombre, descripcion) values (10, 'Basic Industries', 'Major Chemicals');
insert into giro (giro_id, nombre, descripcion) values (11, 'Health Care', 'Precision Instruments');
insert into giro (giro_id, nombre, descripcion) values (12, 'Health Care', 'Other Pharmaceuticals');
insert into giro (giro_id, nombre, descripcion) values (13, 'Public Utilities', 'Natural Gas Distribution');
insert into giro (giro_id, nombre, descripcion) values (14, 'Consumer Services', 'Other Consumer Services');
insert into giro (giro_id, nombre, descripcion) values (15, 'Consumer Services', 'Consumer Electronics/Video Chains');
insert into giro (giro_id, nombre, descripcion) values (16, 'Finance', 'Finance: Consumer Services');
insert into giro (giro_id, nombre, descripcion) values (17, 'Technology', 'Semiconductors');
insert into giro (giro_id, nombre, descripcion) values (18, 'Energy', 'Integrated oil Companies');
insert into giro (giro_id, nombre, descripcion) values (19, 'Consumer Non-Durables', 'Package Goods/Cosmetics');
insert into giro (giro_id, nombre, descripcion) values (20, 'Consumer Services', 'Clothing/Shoe/Accessory Stores');
insert into giro (giro_id, nombre, descripcion) values (21, 'Miscellaneous', 'Industrial Machinery/Components');
insert into giro (giro_id, nombre, descripcion) values (22, 'Consumer Services', 'Restaurants');
