insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (1, to_date('23/02/2020', 'DD/MM/YYYY'), 66, 18);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (2, to_date('23/08/2020', 'DD/MM/YYYY'), 92, 8);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (3, to_date('09/12/2019', 'DD/MM/YYYY'), 29, 4);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (4, to_date('12/12/2019', 'DD/MM/YYYY'), 69, 8);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (5, to_date('02/10/2020', 'DD/MM/YYYY'), 90, 18);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (6, to_date('13/11/2019', 'DD/MM/YYYY'), 9, 15);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (7, to_date('15/10/2020', 'DD/MM/YYYY'), 12, 6);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (8, to_date('25/05/2020', 'DD/MM/YYYY'), 52, 18);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (9, to_date('28/07/2020', 'DD/MM/YYYY'), 18, 3);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (10,to_date('14/03/2020', 'DD/MM/YYYY'), 73, 14);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (11,to_date('05/04/2020', 'DD/MM/YYYY'), 15, 17);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (12,to_date('15/09/2020', 'DD/MM/YYYY'), 96, 3);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (13,to_date('21/05/2020', 'DD/MM/YYYY'), 99, 10);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (14,to_date('28/06/2020', 'DD/MM/YYYY'), 35, 2);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (15,to_date('17/12/2019', 'DD/MM/YYYY'), 80, 15);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (16,to_date('12/07/2020', 'DD/MM/YYYY'), 75, 14);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (17,to_date('25/07/2020', 'DD/MM/YYYY'), 93, 17);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (18,to_date('31/10/2019', 'DD/MM/YYYY'), 42, 2);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (19,to_date('25/09/2020', 'DD/MM/YYYY'), 35, 5);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (20,to_date('28/04/2020', 'DD/MM/YYYY'), 70, 3);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (21,to_date('07/11/2019', 'DD/MM/YYYY'), 70, 17);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (22,to_date('25/01/2020', 'DD/MM/YYYY'), 93, 1);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (23,to_date('24/09/2020', 'DD/MM/YYYY'), 93, 11);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (24,to_date('20/06/2020', 'DD/MM/YYYY'), 62, 8);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (25,to_date('05/12/2019', 'DD/MM/YYYY'), 8, 5);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (26,to_date('15/06/2020', 'DD/MM/YYYY'), 54, 7);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (27,to_date('12/09/2020', 'DD/MM/YYYY'), 3, 6);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (28,to_date('14/10/2020', 'DD/MM/YYYY'), 15, 9);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (29,to_date('14/09/2020', 'DD/MM/YYYY'), 10, 3);
insert into ofertas_guardadas (oferta_personalizada_id, fecha, cliente_id, oferta_id) values (30,to_date('15/10/2020', 'DD/MM/YYYY'), 33, 5);
