--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      HP Inc.
-- Project :      ModeloFisico.DM1
-- Author :       samygarrido1@hotmail.com
--
-- Date Created : Friday, October 16, 2020 23:21:46
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: TIENDA 
--

CREATE TABLE TIENDA(
    TIENDA_ID      NUMBER(10, 0)    NOT NULL,
    NOMBRE         VARCHAR2(40)     NOT NULL,
    DESCRIPCION    VARCHAR2(100)    NOT NULL,
    LOGO           VARCHAR2(200)    NOT NULL,
    LATITUD        NUMBER(8, 5)     NOT NULL,
    LONGITUD       NUMBER(8, 5)     NOT NULL,
    HORA_INICIO    DATE             NOT NULL,
    HORA_FIN       DATE             NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (TIENDA_ID)
)
;



-- 
-- TABLE: GIRO 
--

CREATE TABLE GIRO(
    GIRO_ID        NUMBER(10, 0)    NOT NULL,
    NOMBRE         VARCHAR2(40)     NOT NULL,
    DESCRIPCION    VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK20 PRIMARY KEY (GIRO_ID)
)
;



-- 
-- TABLE: OFERTA 
--

CREATE TABLE OFERTA(
    OFERTA_ID               NUMBER(10, 0)    NOT NULL,
    TIPO                    NUMBER(40, 0)    NOT NULL,
    NOMBRE                  VARCHAR2(40)     NOT NULL,
    DESCRIPCION             VARCHAR2(300)    NOT NULL,
    TERMINOS_CONDICIONES    VARCHAR2(200)    NOT NULL,
    IMAGEN                  VARCHAR2(200)    NOT NULL,
    FECHA_INICIO            DATE             NOT NULL,
    FECHA_FIN               DATE             NOT NULL,
    TIENDA_ID               NUMBER(10, 0),
    GIRO_ID                 NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK11 PRIMARY KEY (OFERTA_ID), 
    CONSTRAINT RefTIENDA1 FOREIGN KEY (TIENDA_ID)
    REFERENCES TIENDA(TIENDA_ID),
    CONSTRAINT RefGIRO8 FOREIGN KEY (GIRO_ID)
    REFERENCES GIRO(GIRO_ID)
)
;



-- 
-- TABLE: TIPO_TARJETA_CREDITO 
--

CREATE TABLE TIPO_TARJETA_CREDITO(
    TIPO_TARJETA_ID    VARCHAR2(40)    NOT NULL,
    DESCRIPCION        VARCHAR2(40)    NOT NULL,
    NOMBRE             VARCHAR2(40)    NOT NULL,
    CONSTRAINT PK36 PRIMARY KEY (TIPO_TARJETA_ID)
)
;



-- 
-- TABLE: BBENEFICIO 
--

CREATE TABLE BBENEFICIO(
    BENEFICIO_ID    VARCHAR2(40)    NOT NULL,
    CLAVE           VARCHAR2(40)    NOT NULL,
    DESCRIPCION     VARCHAR2(40)    NOT NULL,
    CONSTRAINT PK37 PRIMARY KEY (BENEFICIO_ID)
)
;



-- 
-- TABLE: ASOCIADOS 
--

CREATE TABLE ASOCIADOS(
    OFERTA_ID          NUMBER(10, 0)    NOT NULL,
    CANTIDAD           VARCHAR2(40)     NOT NULL,
    TIPO_TARJETA_ID    VARCHAR2(40)     NOT NULL,
    BENEFICIO_ID       VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK24 PRIMARY KEY (OFERTA_ID), 
    CONSTRAINT RefOFERTA9 FOREIGN KEY (OFERTA_ID)
    REFERENCES OFERTA(OFERTA_ID),
    CONSTRAINT RefTIPO_TARJETA_CREDITO17 FOREIGN KEY (TIPO_TARJETA_ID)
    REFERENCES TIPO_TARJETA_CREDITO(TIPO_TARJETA_ID),
    CONSTRAINT RefBBENEFICIO18 FOREIGN KEY (BENEFICIO_ID)
    REFERENCES BBENEFICIO(BENEFICIO_ID)
)
;



-- 
-- TABLE: CLIENTE 
--

CREATE TABLE CLIENTE(
    CLIENTE_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE        VARCHAR2(50)     NOT NULL,
    AP_PATERNO    VARCHAR2(40)     NOT NULL,
    AP_MATERNO    VARCHAR2(40),
    CURP          VARCHAR2(18)     NOT NULL,
    RFC           VARCHAR2(13)     NOT NULL,
    TELEFONO      VARCHAR2(10)     NOT NULL,
    CONTRASENA    VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (CLIENTE_ID)
)
;



-- 
-- TABLE: CREDITO_PREAPROBADO 
--

CREATE TABLE CREDITO_PREAPROBADO(
    OFERTA_ID    NUMBER(10, 0)    NOT NULL,
    MONTO        NUMBER(10, 2)    NOT NULL,
    INTERES      NUMBER(6, 3)     NOT NULL,
    CONSTRAINT PK16 PRIMARY KEY (OFERTA_ID), 
    CONSTRAINT RefOFERTA3 FOREIGN KEY (OFERTA_ID)
    REFERENCES OFERTA(OFERTA_ID)
)
;



-- 
-- TABLE: CUENTA 
--

CREATE TABLE CUENTA(
    CUENTA_ID        VARCHAR2(40)     NOT NULL,
    NUMERO_CUENTA    VARCHAR2(40)     NOT NULL,
    CLIENTE_ID       NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK32 PRIMARY KEY (CUENTA_ID), 
    CONSTRAINT RefCLIENTE12 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: MOVIMIENTO 
--

CREATE TABLE MOVIMIENTO(
    MOVIMIENTO_ID       VARCHAR2(40)     NOT NULL,
    DESCRIPCION         VARCHAR2(40)     NOT NULL,
    MONTO               NUMBER(12, 3)    NOT NULL,
    FECHA_MOVIMIENTO    TIMESTAMP(6)     NOT NULL,
    CUENTA_ID           VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK31 PRIMARY KEY (MOVIMIENTO_ID), 
    CONSTRAINT RefCUENTA13 FOREIGN KEY (CUENTA_ID)
    REFERENCES CUENTA(CUENTA_ID)
)
;



-- 
-- TABLE: OFERTA_PERSONAL 
--

CREATE TABLE OFERTA_PERSONAL(
    OFERTA_PERSONAL_ID    VARCHAR2(40)     NOT NULL,
    OFERTA_ID             NUMBER(10, 0)    NOT NULL,
    CUENTA_ID             VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK25 PRIMARY KEY (OFERTA_PERSONAL_ID), 
    CONSTRAINT RefOFERTA10 FOREIGN KEY (OFERTA_ID)
    REFERENCES OFERTA(OFERTA_ID),
    CONSTRAINT RefCUENTA15 FOREIGN KEY (CUENTA_ID)
    REFERENCES CUENTA(CUENTA_ID)
)
;



-- 
-- TABLE: OFERTAS_GUARDADAS 
--

CREATE TABLE OFERTAS_GUARDADAS(
    OFERTA_PERSONALIZADA_ID    NUMBER(10, 0)    NOT NULL,
    FECHA                      DATE             NOT NULL,
    OFERTA_ID                  NUMBER(10, 0)    NOT NULL,
    CLIENTE_ID                 NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK19 PRIMARY KEY (OFERTA_PERSONALIZADA_ID), 
    CONSTRAINT RefOFERTA6 FOREIGN KEY (OFERTA_ID)
    REFERENCES OFERTA(OFERTA_ID),
    CONSTRAINT RefCLIENTE16 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: TIPO_SEGURO 
--

CREATE TABLE TIPO_SEGURO(
    TIPO_SEGURO    NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(40)     NOT NULL,
    DESCRIPCION    VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK38 PRIMARY KEY (TIPO_SEGURO)
)
;



-- 
-- TABLE: SEGURO 
--

CREATE TABLE SEGURO(
    OFERTA_ID          NUMBER(10, 0)    NOT NULL,
    MONTO_ASEGURADO    NUMBER(20, 2)    NOT NULL,
    PRECIO             NUMBER(8, 2)     NOT NULL,
    DURACION_MESES     NUMBER(5, 0)     NOT NULL,
    TIPO_SEGURO        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK18 PRIMARY KEY (OFERTA_ID), 
    CONSTRAINT RefOFERTA5 FOREIGN KEY (OFERTA_ID)
    REFERENCES OFERTA(OFERTA_ID),
    CONSTRAINT RefTIPO_SEGURO20 FOREIGN KEY (TIPO_SEGURO)
    REFERENCES TIPO_SEGURO(TIPO_SEGURO)
)
;



-- 
-- TABLE: TARJETA 
--

CREATE TABLE TARJETA(
    TARJETA_ID         VARCHAR2(40)    NOT NULL,
    NUMERO_TARJETA     VARCHAR2(40)    NOT NULL,
    CVV                NUMBER(3, 0)    NOT NULL,
    MES                NUMBER(2, 0)    NOT NULL,
    ANIO               NUMBER(4, 0)    NOT NULL,
    CUENTA_ID          VARCHAR2(40)    NOT NULL,
    TIPO_TARJETA_ID    VARCHAR2(40)    NOT NULL,
    CONSTRAINT PK33 PRIMARY KEY (TARJETA_ID), 
    CONSTRAINT RefCUENTA14 FOREIGN KEY (CUENTA_ID)
    REFERENCES CUENTA(CUENTA_ID),
    CONSTRAINT RefTIPO_TARJETA_CREDITO21 FOREIGN KEY (TIPO_TARJETA_ID)
    REFERENCES TIPO_TARJETA_CREDITO(TIPO_TARJETA_ID)
)
;



-- 
-- TABLE: TARJETA_PREAPROBADA 
--

CREATE TABLE TARJETA_PREAPROBADA(
    OFERTA_ID              NUMBER(10, 0)    NOT NULL,
    TARJETA_PREAPROBADA    VARCHAR2(20)     NOT NULL,
    LIMITE_CREDITO         NUMBER(8, 2)     NOT NULL,
    CAT                    NUMBER(6, 2)     NOT NULL,
    ANUALIDAD              NUMBER(8, 2)     NOT NULL,
    CONSTRAINT PK17 PRIMARY KEY (OFERTA_ID), 
    CONSTRAINT RefOFERTA4 FOREIGN KEY (OFERTA_ID)
    REFERENCES OFERTA(OFERTA_ID)
)
;



-- 
-- INDEX: Ref119 
--

CREATE INDEX Ref119 ON ASOCIADOS(OFERTA_ID)
;
-- 
-- INDEX: Ref3617 
--

CREATE INDEX Ref3617 ON ASOCIADOS(TIPO_TARJETA_ID)
;
-- 
-- INDEX: Ref3718 
--

CREATE INDEX Ref3718 ON ASOCIADOS(BENEFICIO_ID)
;
-- 
-- INDEX: Ref113 
--

CREATE INDEX Ref113 ON CREDITO_PREAPROBADO(OFERTA_ID)
;
-- 
-- INDEX: Ref712 
--

CREATE INDEX Ref712 ON CUENTA(CLIENTE_ID)
;
-- 
-- INDEX: Ref3213 
--

CREATE INDEX Ref3213 ON MOVIMIENTO(CUENTA_ID)
;
-- 
-- INDEX: Ref11 
--

CREATE INDEX Ref11 ON OFERTA(TIENDA_ID)
;
-- 
-- INDEX: Ref208 
--

CREATE INDEX Ref208 ON OFERTA(GIRO_ID)
;
-- 
-- INDEX: Ref1110 
--

CREATE INDEX Ref1110 ON OFERTA_PERSONAL(OFERTA_ID)
;
-- 
-- INDEX: Ref3215 
--

CREATE INDEX Ref3215 ON OFERTA_PERSONAL(CUENTA_ID)
;
-- 
-- INDEX: Ref116 
--

CREATE INDEX Ref116 ON OFERTAS_GUARDADAS(OFERTA_ID)
;
-- 
-- INDEX: Ref716 
--

CREATE INDEX Ref716 ON OFERTAS_GUARDADAS(CLIENTE_ID)
;
-- 
-- INDEX: Ref115 
--

CREATE INDEX Ref115 ON SEGURO(OFERTA_ID)
;
-- 
-- INDEX: Ref3820 
--

CREATE INDEX Ref3820 ON SEGURO(TIPO_SEGURO)
;
-- 
-- INDEX: Ref3214 
--

CREATE INDEX Ref3214 ON TARJETA(CUENTA_ID)
;
-- 
-- INDEX: Ref3621 
--

CREATE INDEX Ref3621 ON TARJETA(TIPO_TARJETA_ID)
;
-- 
-- INDEX: Ref114 
--

CREATE INDEX Ref114 ON TARJETA_PREAPROBADA(OFERTA_ID)
;
